package clasesHibernate;
// Generated 10 feb 2025 18:53:06 by Hibernate Tools 6.5.1.Final

/**
 * Alojamientosturismorural generated by hbm2java
 */
public class Alojamientosturismorural implements java.io.Serializable {

	private int id;
	private Tipos tipos;
	private Provincias provincias;
	private String categoria;
	private String nombre;
	private String direccion;
	private String cp;
	private String localidad;
	private String telefono;

	public Alojamientosturismorural() {
	}

	public Alojamientosturismorural(int id, String nombre, String direccion, String cp, String localidad,
			String telefono) {
		this.id = id;
		this.nombre = nombre;
		this.direccion = direccion;
		this.cp = cp;
		this.localidad = localidad;
		this.telefono = telefono;
	}

	public Alojamientosturismorural(int id, Tipos tipos, Provincias provincias, String categoria, String nombre,
			String direccion, String cp, String localidad, String telefono) {
		this.id = id;
		this.tipos = tipos;
		this.provincias = provincias;
		this.categoria = categoria;
		this.nombre = nombre;
		this.direccion = direccion;
		this.cp = cp;
		this.localidad = localidad;
		this.telefono = telefono;
	}

	
	public Alojamientosturismorural(String nombre, String direccion, String cp, String localidad,
			String telefono) {
		this.nombre = nombre;
		this.direccion = direccion;
		this.cp = cp;
		this.localidad = localidad;
		this.telefono = telefono;
	}

	public Alojamientosturismorural(Tipos tipos, Provincias provincias, String categoria, String nombre,
			String direccion, String cp, String localidad, String telefono) {
		this.tipos = tipos;
		this.provincias = provincias;
		this.categoria = categoria;
		this.nombre = nombre;
		this.direccion = direccion;
		this.cp = cp;
		this.localidad = localidad;
		this.telefono = telefono;
	}

	
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Tipos getTipos() {
		return this.tipos;
	}

	public void setTipos(Tipos tipos) {
		this.tipos = tipos;
	}

	public Provincias getProvincias() {
		return this.provincias;
	}

	public void setProvincias(Provincias provincias) {
		this.provincias = provincias;
	}

	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getCp() {
		return this.cp;
	}

	public void setCp(String cp) {
		this.cp = cp;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

}
